"""Teaching utilities for SEMTM0009 continuous-time model analysis."""

__version__ = "0.1.0"

from .analysis import (
    Equilibrium,
    classify_eigenvalues,
    find_equilibria,
    numerical_jacobian,
    simulate,
)
from .continuation import (
    ContinuationBranch,
    PeriodicBranch,
    continue_equilibria,
    continue_periodic_orbits,
)
from .continuation_api import continue_equilibrium, continue_periodic_orbit
from .models import (
    brusselator,
    fitzhugh_nagumo,
    lorenz,
    morris_lecar_bursting,
    repressilator,
    seir,
    sir,
    toggle_switch,
)
from .plotting import (
    evaluate_vector_field,
    phase_portrait,
    plot_equilibria,
    plot_nullclines,
    plot_trajectories,
    plot_vector_field,
    state_grid,
)
from .reduced_neuron import (
    IZHIKEVICH_PRACTICAL_PARAMETERS,
    analytical_jacobian,
    m_infinity,
    n_infinity,
    reduced_neuron,
    steady_gate,
    voltage_nullcline,
)
from .types import (
    BrusselatorParameters,
    FHNParameters,
    ComplexArray,
    FloatArray,
    LorenzParameters,
    MorrisLecarParameters,
    Parameters,
    RepressilatorParameters,
    RHS,
    SEIRParameters,
    SIRParameters,
    ToggleParameters,
)

__all__ = [
    "brusselator",
    "BrusselatorParameters",
    "ContinuationBranch",
    "ComplexArray",
    "Equilibrium",
    "PeriodicBranch",
    "classify_eigenvalues",
    "continue_equilibria",
    "continue_equilibrium",
    "continue_periodic_orbit",
    "continue_periodic_orbits",
    "find_equilibria",
    "fitzhugh_nagumo",
    "FHNParameters",
    "FloatArray",
    "lorenz",
    "IZHIKEVICH_PRACTICAL_PARAMETERS",
    "analytical_jacobian",
    "m_infinity",
    "morris_lecar_bursting",
    "MorrisLecarParameters",
    "LorenzParameters",
    "evaluate_vector_field",
    "numerical_jacobian",
    "n_infinity",
    "phase_portrait",
    "Parameters",
    "plot_equilibria",
    "plot_nullclines",
    "plot_trajectories",
    "plot_vector_field",
    "simulate",
    "repressilator",
    "reduced_neuron",
    "RepressilatorParameters",
    "RHS",
    "seir",
    "SEIRParameters",
    "sir",
    "SIRParameters",
    "state_grid",
    "steady_gate",
    "toggle_switch",
    "ToggleParameters",
    "voltage_nullcline",
    "__version__",
]
